version: "3.7"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vacc__bot
    image: vacc__bot:0.0.1
    env_file:
      - .env
    restart: on-failure:10
